### ISSUE TITLE
/instrument/touch/top middle bottom calculation for 5G - Need firmware update

### ISSUE THREAD

**Issue by Gael514** [IDMIL/tstick-docs#10]
5G T-Sticks now have 30 touch sensors compared to 16 previously.
Top and bottom areas still seem to correspond to 4 touch sensors (legacy of previous generations). Which means middle section contains 22 sensors!

There should a discussion to decide how the 3 sections should be split and update the firmware accordingly. Older T-Sticks were 4-8-4 (25%-50%-25%).
7-16-7 and 8-14-8 would be closest  to existing T-Sticks. Or do we want to go 10-10-10?

**Comment by aburt2** [comment]
@edumeneses can you look at this in the puara gestures repository
