### ISSUE TITLE
Frimware flashing issue: -DTSTICK_SIZE overwritten by tstick-presets.h

### ISSUE THREAD

**Issue by Gael514** [IDMIL/tstick-docs#11]
The number of capsense -DTSTICK_SIZE entered for the build flags in _platformio.ini_ is overwritten by the value in _src/tstick-presets.h_.
Firmware should be corrected.

**Comment by aburt2** [comment]
@Gael514 this a firmware issue can you put this in the t-stick firmware repository: https://github.com/aburt2/T-Stick/issues
