### ISSUE TITLE
T_Stick_5gw_trill_images

### ISSUE THREAD

**Issue by Echo078** [IDMIL/tstick-docs#8]
[tstick_5_triill_part1.zip](https://github.com/user-attachments/files/16341337/tstick_5_triill_part1.zip)
[tstick_5_trill_part2.zip](https://github.com/user-attachments/files/16341338/tstick_5_trill_part2.zip)

**Comment by aburt2** [comment]
Related to build guide update #5

**Comment by aburt2** [comment]
added pictures to documentation site closing issue
